---
type: replica
setName: repl0
default_args: -v --bind_ip 0.0.0.0 --quiet
mongod:
    - name: host1
      port_override: 27017
    - name: host2
      port_override: 27018
    - name: host3
      port_override: 27019

# vim: ts=4 sts=4 sw=4 et:
