---
type: replica
setName: foo
default_args: -v --noprealloc --smallfiles --bind_ip 0.0.0.0 --nssize 6 --quiet
default_version: 4.0
mongod:
    - name: host1
    - name: host2
    - name: host3
      rs_config:
          arbiterOnly: true

# vim: ts=4 sts=4 sw=4 et:
