---
type: replica
setName: foo
default_args: -v --noprealloc --smallfiles --bind_ip 0.0.0.0 --nssize 6 --quiet
default_version: 3.6
mongod:
    - name: host1
    - name: host2
    - name: host3

# vim: ts=4 sts=4 sw=4 et:
